debian_iso_checksum   = "file:https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/SHA512SUMS"
debian_iso_url        = "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-13.4.0-amd64-netinst.iso"
debian_preseed_file   = "preseed/debian-13.cfg"
scaleway_id           = "a4ec3f48-e0a0-4249-8272-c1dc0dea17d3"
hostname              = "debian-13"
output_dir            = "output-debian-13"
image_name            = "debian-13"
